[project]
name = "Message"
version = "0.1.0"
description = "Message Protocol for Inbox Client"
readme = "README.md"
requires-python = ">=3.11"
  
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
message = { workspace = true }